name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 1. Pull in your code
      - uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build & push
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USER }}/axanth-website:latest
            docker.io/${{ secrets.DOCKERHUB_USER }}/axanth-website:${{ github.sha }}